inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - db/**/*
    - vendor/**/*
    - log/**/*
    - tmp/**/*
    - storage/**/*
    - lib/tasks/**/*
    - bin/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false