import '@hotwired/turbo-rails'
import 'controllers'
import './jquery'
import './jquery_ujs'
import './jquery.validate'
import './jquery.validate.additional-methods'
import './dataTables/jquery.dataTables'
import './cocoon'
