default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prc_api_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: prc_api_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: prc_api_production
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>