plugins:
  - rubocop-rails
  - rubocop-performance
  # - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.7
  TargetRailsVersion: 8.0
  DisplayCopNames: true

  SuggestExtensions: false
  Exclude:
    - db/**/*
    - vendor/**/*
    - log/**/*
    - tmp/**/*
    - storage/**/*
    - bin/*
    - lib/tasks/**/*
    - ai-tools/**/*
    - docx/**/*w
    - public/**/*
    - node_modules/**/*
    - frontend/**/*

    # Arquivos que serão revisados em uma próxima etapa:
    - app/models/procedure.rb
    - app/models/procedural_party.rb
    - app/models/legal_cost.rb
    - app/models/honorary_component.rb
    - app/models/honorary.rb
    - app/services/notification_service.rb

    # Arquivos que serão deprecados:
    - app/services/works/**/*
    - app/services/profile_customers/**/*
    - app/services/draft_fulfillment_example.rb
    - app/services/docx_services/social_contract_test.rb
    - app/services/docx_services/**/*

# Layout Cops
Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Style Cops
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: compact

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/RescueStandardError:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/GlobalVars:
  Enabled: true
  Exclude:
    - spec/**/*

# Metrics Cops
Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200
  Exclude:
    - spec/**/*
    - app/controllers/api/v1/jobs_controller.rb
    - app/controllers/api/v1/user_profiles_controller.rb

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Max: 25
  Exclude:
    - spec/**/*
    - config/**/*
    - db/migrate/*
    - lib/tasks/**/*

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 5

# Naming Cops
Naming/PredicatePrefix:
  Enabled: true
  ForbiddenPrefixes:
    - is_

Naming/VariableName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

# Rails Cops
Rails:
  Enabled: true

# Disable Rails/StrongParametersExpect cop that converts require().permit() to expect()
# This is needed for nested attributes to work properly with complex nested hashes
Rails/StrongParametersExpect:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/Output:
  Enabled: true
  Exclude:
    - db/seeds.rb

Rails/SkipsModelValidations:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: true

# RSpec configuration removed for now due to compatibility issues
# Can be re-added when using a compatible version

# Performance Cops
Performance:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/StringReplacement:
  Enabled: true
